AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::618244506016:role/lambdaExecutionRole11030037
      Code:
        S3Bucket: testdeploymentbucketdatalakes
        S3Key: 178963/code.zip
      Runtime: python3.8
      Timeout: 15